FROM mvangala/base-ubuntu:latest 

MAINTAINER Mahesh Vangala <vangalamaheshh@gmail.com>

RUN set -ex \
    && git clone https://github.com/alexdobin/STAR.git

ENV PATH /usr/local/bin/STAR/bin/Linux_x86_64_static:$PATH

