FROM ubuntu:16.04

MAINTAINER Mahesh Vangala <vangalamaheshh@gmail.com>

RUN set -ex \
  && apt-get -y update \
  && apt-get -y install vim curl dialog net-tools nginx

COPY nginx.conf /etc/nginx/nginx.conf

RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf

EXPOSE 80

EXPOSE 443

CMD service nginx start
