FROM mvangala/base-nginx:python3.6 

MAINTAINER Mahesh Vangala <vangalamaheshh@gmail.com>

RUN set -ex \
  && pip install flask requests \
  && pip install flask-cors 

RUN set -ex \
  && mkdir -p /usr/local/bin

WORKDIR /usr/local/bin

RUN set -ex \
  && apt-get update -y \
  && apt-get install -y unzip \
  && apt-get install -y vim \
  && apt-get install -y git \
  && apt-get install -y wget \
  && apt-get install -y bzip2 \
  && apt-get install -y curl

# install miniconda3
RUN set -ex \
  && wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
  && bash Miniconda3-latest-Linux-x86_64.sh -b -p /usr/local/bin/miniconda3

ENV PATH /usr/local/bin/miniconda3/bin:$PATH

#COPY ./annovar.latest.tar.gz /usr/local/bin/annovar.latest.tar.gz

#RUN set -ex \
#  && tar -zxvf /usr/local/bin/annovar.latest.tar.gz

#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_esp6500siv2_all.txt.gz \ 
#    http://www.openbioinformatics.org/annovar/download/hg19_esp6500siv2_all.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_esp6500siv2_all.txt.idx.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_esp6500siv2_all.txt.idx.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_1000g2015aug.zip \
#    http://www.openbioinformatics.org/annovar/download/hg19_1000g2015aug.zip
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_avsnp147.txt.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_avsnp147.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_avsnp147.txt.idx.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_avsnp147.txt.idx.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_dbnsfp33a.txt.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_dbnsfp33a.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_dbnsfp33a.txt.idx.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_dbnsfp33a.txt.idx.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_clinvar_20170905.txt.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_clinvar_20170905.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_clinvar_20170905.txt.idx.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_clinvar_20170905.txt.idx.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_exac03.txt.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_exac03.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_exac03.txt.idx.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_exac03.txt.idx.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_dbscsnv11.txt.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_dbscsnv11.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_dbscsnv11.txt.idx.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_dbscsnv11.txt.idx.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_dbnsfp31a_interpro.txt.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_dbnsfp31a_interpro.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_dbnsfp31a_interpro.txt.idx.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_dbnsfp31a_interpro.txt.idx.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/rmsk.txt.gz \
#    http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/rmsk.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_ensGene.txt.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_ensGene.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_ensGeneMrna.fa.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_ensGeneMrna.fa.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_knownGene.txt.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_knownGene.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_kgXref.txt.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_kgXref.txt.gz
#RUN set -ex \
#  && wget -O /usr/local/bin/annovar/humandb/hg19_knownGeneMrna.fa.gz \
#    http://www.openbioinformatics.org/annovar/download/hg19_knownGeneMrna.fa.gz
#
#RUN set -ex \
#  && unzip /usr/local/bin/annovar/humandb/hg19_1000g2015aug.zip -d /usr/local/bin/annovar/humandb/ 

#RUN set -ex \
#  && gunzip /usr/local/bin/annovar/humandb/*.gz

#RUN set -ex \
#  && rm /usr/local/bin/annovar/humandb/*rmsk.tx* \
#  && wget -O /usr/local/bin/annovar/humandb/rmsk.txt.gz \
#    http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/rmsk.txt.gz \
#  && gunzip /usr/local/bin/annovar/humandb/rmsk.txt.gz

#RUN set -ex \
#  && apt-get install -y less gawk \
#  && gawk '{if(NF == 17) { print $0;}}' /usr/local/bin/annovar/humandb/rmsk.txt \
#    1>/usr/local/bin/annovar/humandb/hg19_rmsk.txt

RUN set -ex \
#  && rm -rf /usr/local/bin/Intervar \
#  && rm -rf /usr/local/bin/AVA \
#  && git clone https://github.com/vangalamaheshh/Intervar.git \
#  && chmod 755 /usr/local/bin/Intervar/Intervar.py \
  && git clone https://github.com/dst-umms/AVA.git \
  && conda env update -f /usr/local/bin/AVA/env/requirements.yaml \
  && conda env create -f /usr/local/bin/AVA/env/py2_env.yaml

RUN set -ex \
  && gunzip /usr/local/bin/AVA/server/utils/db/clinvar/clinvar_20180701.vcf.gz

#COPY ./mim2gene.txt /usr/local/bin/Intervar/intervardb/mim2gene.txt
# set up flask with nginx
# By default, allow unlimited file sizes, modify it to limit the file sizes
# To have a maximum of 1 MB (Nginx's default) change the line to:
# ENV NGINX_MAX_UPLOAD 1m
ENV NGINX_MAX_UPLOAD 0

# Which uWSGI .ini file should be used, to make it customizable
ENV UWSGI_INI /usr/local/bin/AVA/server/uwsgi.ini
# URL under which static (not modified by Python) files will be requested
# They will be served by Nginx directly, without being handled by uWSGI
ENV STATIC_URL /static
# Absolute path in where the static files wil be
ENV STATIC_PATH /usr/local/bin/AVA
# If STATIC_INDEX is 1, serve / with /static/index.html directly (or the static URL configured)
# ENV STATIC_INDEX 1
ENV STATIC_INDEX 0
# Copy the entrypoint that will generate Nginx additional configs
COPY uwsgi.ini /usr/local/bin/AVA/server/uwsgi.ini
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


WORKDIR /usr/local/bin/AVA/server

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/bin/supervisord"]


