version: "2"

services:
  nginx:
    image: mvangala/bioifx_variant_ava-nginx:latest 
    ports:
      - "80:80"
    depends_on:
      - ava-client
      - ava-server
    networks:
      - avanet

  ava-client:
    image: mvangala/bioifx_variant_ava-client:latest
    networks:
      - avanet

  ava-server:  
    image: mvangala/bioifx_variant_ava-server:latest
    networks:
      - avanet

networks:
  avanet:
