/* login with shrine_ont creds and insert following rows using shrine_ont database */
/* I2b2 1.5 convention: Holds the SHRINE Ontology Table */
   CREATE TABLE SHRINE 
   (
    C_HLEVEL NUMERIC(22,0),
  C_FULLNAME VARCHAR(900), 
  C_NAME VARCHAR(2000), 
  C_SYNONYM_CD CHAR(1), 
  C_VISUALATTRIBUTES CHAR(3), 
  C_TOTALNUM NUMERIC(22,0), 
  C_BASECODE VARCHAR(450), 
  C_METADATAXML VARCHAR, 
  C_FACTTABLECOLUMN VARCHAR(50), 
  C_TABLENAME VARCHAR(50), 
  C_COLUMNNAME VARCHAR(50), 
  C_COLUMNDATATYPE VARCHAR(50), 
  C_OPERATOR VARCHAR(10), 
  C_DIMCODE VARCHAR(900), 
  C_COMMENT VARCHAR, 
  C_TOOLTIP VARCHAR(900), 
  UPDATE_DATE DATETIME, 
  DOWNLOAD_DATE DATETIME, 
  IMPORT_DATE DATETIME, 
  SOURCESYSTEM_CD VARCHAR(50), 
  VALUETYPE_CD VARCHAR(50),
        M_APPLIED_PATH VARCHAR(900),
        M_EXCLUSION_CD VARCHAR(900)
   ) ;

/* I2b2 1.5 convention: Governs access to the SHRINE Ont table */
  CREATE TABLE TABLE_ACCESS
   (
    C_TABLE_CD VARCHAR(50),
  C_TABLE_NAME VARCHAR(50), 
  C_PROTECTED_ACCESS CHAR(1),
  C_HLEVEL NUMERIC(22,0), 
  C_FULLNAME VARCHAR(900), 
  C_NAME VARCHAR(2000), 
  C_SYNONYM_CD CHAR(1), 
  C_VISUALATTRIBUTES CHAR(3), 
  C_TOTALNUM NUMERIC(22,0), 
  C_BASECODE VARCHAR(450), 
  C_METADATAXML VARCHAR, 
  C_FACTTABLECOLUMN VARCHAR(50), 
  C_DIMTABLENAME VARCHAR(50), 
  C_COLUMNNAME VARCHAR(50), 
  C_COLUMNDATATYPE VARCHAR(50), 
  C_OPERATOR VARCHAR(10), 
  C_DIMCODE VARCHAR(900), 
  C_COMMENT VARCHAR, 
  C_TOOLTIP VARCHAR(900), 
  C_ENTRY_DATE DATETIME, 
  C_CHANGE_DATE DATETIME, 
  C_STATUS_CD CHAR(1), 
  VALUETYPE_CD VARCHAR(50)
   ) ;

/* TODO: not sure how this is actually loaded up */
   CREATE TABLE  SCHEMES
   (
    C_KEY VARCHAR(50) NOT NULL,
  C_NAME VARCHAR(50) NOT NULL,
  C_DESCRIPTION VARCHAR(100),
   CONSTRAINT SCHEMES_PK PRIMARY KEY (C_KEY)
   )
   ;

GO
QUIT
