CREATE DATABASE OMOP;
GO
USE OMOP;
GO

/* CRC Data User */
CREATE LOGIN i2b2demodata WITH PASSWORD = 'Demou$er';
CREATE USER i2b2demodata FOR LOGIN i2b2demodata;
GRANT CREATE TABLE, SELECT, INSERT, DELETE, UPDATE TO i2b2demodata;
GO

/* Hive Data User */
CREATE LOGIN i2b2hive WITH PASSWORD = 'Demou$er';
CREATE USER i2b2hive FOR LOGIN i2b2hive;
GRANT CREATE TABLE, SELECT, INSERT, DELETE, UPDATE TO i2b2hive;
GO

/* IM Data User */
CREATE LOGIN i2b2imdata WITH PASSWORD = 'Demou$er';
CREATE USER i2b2imdata FOR LOGIN i2b2imdata;
GRANT CREATE TABLE, SELECT, INSERT, DELETE, UPDATE TO i2b2imdata;
GO

/* Meta Data User */
CREATE LOGIN i2b2metadata WITH PASSWORD = 'Demou$er';
CREATE USER i2b2metadata FOR LOGIN i2b2metadata;
GRANT CREATE TABLE, SELECT, INSERT, DELETE, UPDATE TO i2b2metadata;
GO

/* PM Data User */
CREATE LOGIN i2b2pm WITH PASSWORD = 'Demou$er';
CREATE USER i2b2pm FOR LOGIN i2b2pm;
GRANT CREATE TABLE, SELECT, INSERT, DELETE, UPDATE TO i2b2pm;
GO

/* Work Data User */
CREATE LOGIN i2b2workdata WITH PASSWORD = 'Demou$er';
CREATE USER i2b2workdata FOR LOGIN i2b2workdata;
GRANT CREATE TABLE, SELECT, INSERT, DELETE, UPDATE TO i2b2workdata;
GO

QUIT
